# Generated by Django 4.0 on 2022-03-12 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Technical'), ('2', 'Commercial'), ('3', 'Performance'), ('4', 'Health and Safety'), ('5', 'External'), ('6', 'Subs')], max_length=1)),
                ('desc', models.TextField()),
                ('probability', models.CharField(choices=[('1', 'Very Unlikely'), ('2', 'Unlikely'), ('3', 'Moderately Likely'), ('4', 'Likely'), ('5', 'Very Likely')], max_length=1)),
                ('impact', models.CharField(choices=[('1', 'Negligible'), ('2', 'Marginal'), ('3', 'Significant'), ('4', 'Critical'), ('5', 'Unacceptable/Crisis')], max_length=1)),
                ('status', models.CharField(choices=[('1', 'Open'), ('2', 'In progress'), ('3', 'Closed')], max_length=1)),
                ('mitigation', models.TextField()),
                ('cl_costs', models.IntegerField()),
                ('planned_costs', models.IntegerField()),
                ('cont_costs', models.IntegerField()),
                ('costs_in_budget', models.IntegerField()),
                ('owner', models.CharField(max_length=20)),
                ('nearest_month', models.CharField(max_length=20)),
                ('project_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Routes.projects')),
            ],
        ),
    ]
