# Generated by Django 4.0 on 2022-03-23 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0002_risks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risks',
            name='project_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Routes.projects'),
        ),
    ]
