# Generated by Django 4.0 on 2022-03-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0003_alter_risks_project_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risks',
            old_name='project_no',
            new_name='projects',
        ),
    ]
