# Generated by Django 4.0 on 2022-06-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0005_remove_risks_impact_remove_risks_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risks',
            name='cost_of_aft_mitigation',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='risks',
            name='cost_of_bef_mitigation',
            field=models.IntegerField(default=100000),
        ),
    ]
